- coreapi/main_api.py
embedding are now being cached in Video Processing . It has enhanced the video processing part a great margin.
> Embedcache

- coreapi/main_api.py
- corelib/constant.py
It uses Tensorflow serving for deploying the facial expression model
> Facial Expression of faces in image

- coreapi/main_api.py
- corelib/facenet/utils.py
> Documentation

- coreapi/main_api.py
> adding workflow in FaceRecogniseInVideo

- .dockerignore
- .gitignore
- Dockerfile
- Rekognition/settings.py
- download_model.sh
- heroku.yml
- requirements.txt
> Docker support

- coreapi/views.py
> [FIX: #56] Removed redundant checks in class based views coreapi/views.py

- coreapi/models.py
The __str__ method now returns the title of the object. 
Another minor bug, *kwargs was being passed with super constructor in the model's save meathod.
> Fix Model's __str__ to return a string not uuid4 also save method fix

- coreapi/main_api.py
Documentation for nsfwClassifier added
#64
> Adds Docstrings

- coreapi/main_api.py
- coreapi/views.py
- corelib/facenet/utils.py
- templates/predict_result.html
> Fix: multiple face recognition + draw bounding box

- coreapi/main_api.py
- coreapi/retina_net.py
- coreapi/serializers.py
- coreapi/views.py
- corelib/RetinaFace/retina_net.py
I have added RetinaFace for Face Detection. It also provides the face landmarks like eyes, nose and mouth coordinates.
I have also setup tensorflow-serving for RetinaFace model.
Modified TFSModels.zip available here : https://drive.google.com/file/d/1ndw0QZh0XsUv3BjHQzwiekHyoxqyoU43/view?usp=sharing
> ADD: RetinaFace interface for Face Detection

- coreapi/main_api.py
> Display error message when no face in reference image

- coreapi/main_api.py
- coreapi/views.py
> Documentation [WIP]

- logger/__init__.py
- logger/logging.py
> Setting up logger

- coreapi/main_api.py
- coreapi/views.py
Increases modularity of code and facilitates easy testing
> Makes main_api.py independant of django

- coreapi/main_api.py
- corelib/CRNN/CRNN_utils.py
- corelib/constant.py
- requirements.txt
#87
Scene Text Recognition is implemented and models deployed to TFS
Implemented in tensorflow: https://arxiv.org/abs/1507.05717
Examples :
> Feature added : Scene Text Recognition to read the localised text

- coreapi/main_api.py
- coreapi/urls.py
- coreapi/views.py
> Text Extraction from videos

- coreapi/main_api.py
- coreapi/urls.py
- coreapi/views.py
> Object Detection from videos

- .env.dev
- Dockerfile
- docker-compose.yml
- entrypoint.sh
> Containerise the project

- corelib/CRNN/CRNN_utils.py
- corelib/RetinaFace/retina_net.py
- corelib/facenet/align/detect_face.py
While browsing through the Code and studying it for better understanding, I found minor bugs and anti-patterns that can be possibly improved to mitigate any potential bug. Since this is the first time, when I'm contributing to @CCExtractor, I wanted to get a better understanding of the Codebase and make contributions on the same. 
The following commits have been made on the Codebase: 
- Removing the Useless inheritance from Objects
The Issue seems to be very minor but it improves the readability of the Code and since Python 3 inserts it for us behind the scenes, I suggested that its best remove them up.
> Refactored useless inheritance from Objects

- Rekognition/settings.py
- corelib/RetinaFace/retina_net.py
- corelib/constant.py
- corelib/facenet/align/detect_face.py
- corelib/facenet/utils.py
- corelib/main_api.py
- Removed various deprecated SciPy functions
- Used OpenCV alternative for the deprecated SciPy packages
- Made code compatible with TFv2.x
- removed cceface references
**Working Screenshot**
> Updated Facenet to Tensorflow2

- contributing.md
Added steps to download files `char_dict_en.json` and `ord_map_en.json`
> Added steps to download char dict

- corelib/main_api.py
Fixed an issue with **similar face** where skimage was unable to read files sent via request.
> Fixed similar face API

- contributing.md
- corelib/RetinaFace/retina_net.py
- corelib/facenet/utils.py
- corelib/main_api.py
- requirements.txt
(#184 ) Removed scikit-video==1.1.11 and scikit-image==0.14.2 and used OpenCV for performing the same tasks.
> Reduce Dependencies: Removed Scikit Image and Video
